---
title: "Econ Crime Project"
author: "Jonas Bowman, Claire Field, Benn Jesser"
date: "4/26/2021"
output: html_document
---

## Load packages

```{r setup, include=FALSE}

## initial code to rbind the datasets

knitr::opts_chunk$set(echo = TRUE)

library(pacman)
p_load(readr, tidyverse, ggmap, devtools, scales, broom, plotly, stargazer)
```


## Load in the data

```{r data, include=FALSE}
crime2021 = read_csv("CrimeData-2021.csv")


crime2020 = read_csv("CrimeData-2020.csv")


crime2019 = read_csv("CrimeData-2019.csv")
```

## Merge the two datasets

```{r bind}

crime2019 = crime2019 %>% select(-c(OpenDataX, OpenDataY))

#total1 = rbind(crime2021,crime2020)

total1 = rbind(crime2021,crime2020, crime2019)

```

## Format the date, add month column to do seasons later

```{r month}

#format the date column in total1

total1<- total1%>% mutate(date = as.Date.character(total1$OccurDate, format = "%m/%d/%Y")) 


#add a months column
total1 = total1%>%mutate(month = months(date))

##turn month into a name
total1 = total1%>%mutate(month = match(total1$month, month.name))
```

## Create seasons to check out the data

```{r seasons}                        
                         
#create a seasons variable
total1 =total1%>%
  mutate(
    season = case_when(
      month %in% 10:12 ~ "Fall",
      month %in%  1:3  ~ "Winter",
      month %in%  4:6  ~ "Spring",
      TRUE ~ "Summer"))

view(total1)
```

## GGplots of all offenses and only larceny offenses

```{r figure1}
#glimpse(total1)

#ggplot of all offenses by season

offense_gg <- total1%>%ggplot(aes(y=OffenseCategory, fill=season))+geom_bar() +
  xlab("Total Offenses") + ylab("Types of Offenses") + ggtitle("Portland Total Offenses by Season, 2019-2021")

offense_gg

#ggplot of larceny offenses by season


offenses_season <-total1%>%filter(OffenseCategory =="Larceny Offenses")%>%ggplot(aes(y=OffenseType, fill=season))+geom_bar() +
  xlab("Total Larceny Offenses") + ylab("Types of Larceny Offenses") + ggtitle("Portland Larceny by Season, 2019-2021")

offenses_season



##create year and year month variables 

total1 = total1%>%mutate(yr = format(date,"%Y"))

total1 = total1%>%mutate(yr_mth = format(date,"%Y-%m"))


#offense_gg <- total1%>%ggplot(aes(x=OffenseCategory))+geom_bar()

#offenses_season <-total1%>%filter(OffenseCategory =="Assault Offenses")%>%ggplot(aes(x=season))+geom_bar()


##create downtown crime dataset
downtown_crime = total1%>%filter(Neighborhood=="Downtown", yr>="2019") 


downtown_crime =downtown_crime%>%
  group_by(date)%>%
  mutate(total = sum(OffenseCount, na.rm=TRUE))
  
  


##graph that shows the large increae in property crime downtown in summer 2020
  downtown_crime%>%filter(yr=="2020")%>%ggplot(aes(x=date, y=total))+
  geom_line()+theme_minimal()+scale_y_continuous()
  
downtown_crime_vandal <- downtown_crime %>% filter(OffenseCategory=="Vandalism") %>% mutate(total=sum(OffenseCount, na.rm=TRUE))


dates_vline <- as.Date(c("2020-5-29"))         
dates_vline <- which(downtown_crime_vandal$date %in% dates_vline)




downtown_crime_vandal%>%filter(yr=="2020")%>%ggplot(aes(x=date, y=total))+
  geom_line()+theme_minimal()+scale_y_continuous()+geom_vline(xintercept=as.numeric(downtown_crime_vandal$date[dates_vline]),
             col = "red", lwd = 2, alpha =.3)+ geom_smooth(method = "loess", se=F)+
  labs(title="Crime Downtown", x="Date", y="Count")
  
  # I noticed that the filter(Offensecategory was not working because youhave to )
  
  

   
   
total1%>%group_by(date)%>%
  mutate(total = sum(OffenseCount, na.rm=TRUE))%>%
  filter(yr=="2020")%>%ggplot(aes(x=date, y=total, color=CrimeAgainst))+
  geom_line()+theme_minimal()+scale_y_continuous()+
  labs(title="Arrests by Date", x="Date", y="Arrests")



society_crimes = total1%>%filter(CrimeAgainst=="Society")

#society_crimes%>%group_by(OffenseType)%>%summarise(total = sum(OffenseCount, na.rm = TRUE)ggplot(aes(x=yr_mth ,y=total, fill=OffenseType))+geom_line()+theme_minimal()





total1%>%group_by(date)%>%filter(CrimeAgainst=="Property")%>%
  mutate(total = sum(OffenseCount, na.rm=TRUE))%>%
  filter(yr=="2020")%>%ggplot(aes(x=date, y=total))+
  geom_line(color="darkgreen")+theme_minimal()+scale_y_continuous()+
  labs(title="Personal Arrests by Date", x="Date", y="Arrests")





total1%>%group_by(date)%>%
  mutate(total = sum(OffenseCount, na.rm=TRUE))%>%
  filter(yr=="2020")%>%ggplot(aes(x=date, y=total))+
  geom_line(color="red")+theme_minimal()+scale_y_continuous()+
  labs(title="Total Arrests by Date", x="Date", y="Arrests")

```

```{r}
not_downtown_crime <- total1%>%filter(Neighborhood!="Downtown", yr>="2019") 


not_downtown_crime <-not_downtown_crime%>%
  group_by(date)%>%
  mutate(total = sum(OffenseCount, na.rm=TRUE))

dates_vline <- as.Date(c("2020-5-29"))         
dates_vline <- which(downtown_crime_vandal$date %in% dates_vline)

##graph that shows the large increae in property crime downtown in summer 2020
not_downtown_crime%>%filter(yr=="2020")%>%ggplot(aes(x=date, y=total))+
  geom_line()+theme_minimal()+scale_y_continuous()+ labs(title = "Crime Outside of Downtown")+geom_vline(xintercept=as.numeric(downtown_crime_vandal$date[dates_vline]),
             col = "red", lwd = 2, alpha =.3)+ geom_smooth(method = "loess", se=F)


not_downtown_crime_vandal <- not_downtown_crime %>% filter(OffenseCategory=="Vandalism") %>% mutate(total=sum(OffenseCount, na.rm=TRUE))

dates_vline <- as.Date(c("2020-5-29"))         
dates_vline <- which(not_downtown_crime_vandal$date %in% dates_vline)

not_downtown_crime_vandal%>%filter(yr=="2020")%>%ggplot(aes(x=date, y=total))+
  geom_line()+scale_y_continuous()+ labs(title = "Vandalism Outside of Downtown")+geom_vline(xintercept=as.numeric(not_downtown_crime_vandal$date[dates_vline]),
             col = "red", lwd = 2, alpha =.3)+ geom_smooth(method = "loess", se=F)
  


```



## COVID and Crime

```{r rd}
covid_data = filter(total1, between(date, as.Date("2019-03-15"), as.Date("2021-03-15")))

covid_data$crime_count <- ave(as.numeric(covid_data[[1]]), covid_data[["date"]] ,
                                                     FUN=length)

covid_data = covid_data %>% mutate(pandemic = ifelse(date >= "2019-03-15" & date <= "2020-03-15", "Pre", "Peri"))

head(covid_data)


cov_plot <- ggplot(covid_data, aes(date, crime_count, color=factor(pandemic))) + 
  geom_point(size = 1, alpha = 0.1) +
  geom_smooth() + 
  xlab("March 2019 to March 2021") +
  ylab("Crimes per Day") +
  scale_color_discrete(name = "Pandemic") +
  geom_vline(xintercept=as.numeric(as.Date("2020-03-15")), color= "black", linetype = "longdash") +
  ggtitle(label = "Portland Crime: Before and During COVID Pandemic")

cov_plot

cov_plot2 <- ggplot(covid_data, aes(date, crime_count, color=factor(pandemic))) + 
  geom_point(size = 1, alpha = 0.1) +
  geom_smooth(method="lm") + 
  xlab("March 2019 to March 2021") +
  ylab("Crimes per Day") +
  scale_color_discrete(name = "Pandemic") +
  geom_vline(xintercept=as.numeric(as.Date("2020-03-15")), color= "black", linetype = "longdash") +
  ggtitle(label = "Portland Crime: Before and During COVID Pandemic")

cov_plot2

```

```{r covid}

covid_data1 <- covid_data %>% filter(pandemic=="Pre")

covid_data2 <- covid_data %>% filter(pandemic=="Peri")

cov_reg1 = lm(crime_count ~ season, covid_data1)

cov_reg2 = lm(crime_count ~ season, covid_data2)

stargazer(cov_reg1, keep.stat = c("n", "rsq"), model.numbers = FALSE,
          covariate.labels = c("Spring", "Summer", "Winter"),
          dep.var.labels = c("Daily Crime Counts"), type = "text", style = "qje")

stargazer(cov_reg2, keep.stat = c("n", "rsq"), model.numbers = FALSE,
          covariate.labels = c("Spring", "Summer", "Winter"),
          dep.var.labels = c("Daily Crime Counts"), type = "text", style = "qje")

```


